### ISSUE TITLE
Error building Oni after re-basing on master that includes keyboard-layout

### ISSUE THREAD

**Issue by TalAmuyal** [bryphe/oni#765]
When running `npm install` on master (on Ubuntu) I get:

```
> keyboard-layout@2.0.13 install /path/to/project/oni/node_modules/keyboard-layout
> node-gyp rebuild

make: Entering directory '/path/to/project/oni/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o
In file included from ../src/keyboard-layout-manager-linux.cc:1:0:
../src/keyboard-layout-manager.h:7:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
compilation terminated.
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o] Error 1
keyboard-layout-manager.target.mk:96: recipe for target 'Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o' failed
make: Leaving directory '/path/to/project/oni/node_modules/keyboard-layout/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.0-35-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /path/to/project/oni/node_modules/keyboard-layout
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! keyboard-layout@2.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keyboard-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/my-user/.npm/_logs/2017-10-06T11_33_21_501Z-debug.log
```

After executing `sudo apt install libx11-dev` the error is changed to:

```

make: Entering directory '/path/to/project/oni/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o
../src/keyboard-layout-manager-linux.cc:5:37: fatal error: X11/extensions/XKBrules.h: No such file or directory
 #include <X11/extensions/XKBrules.h>
                                     ^
compilation terminated.

...
```

Doesn't seem I am on the right track.

What am I missing/doing wrong?

**Comment by bryphe** [comment]
Hi @TalAmuyal , just responded to you on gitter too. Sorry for the issues here - I believe you also need `libxkbfile-dev` as a dependency. 

Can you try running `sudo apt install libxkbfile-dev` and `npm install` + `npm run build` again and see if that fixes the issue?

I also updated the [Development](https://github.com/bryphe/oni/wiki/Development) section of our wiki with some of these notes

**Comment by TalAmuyal** [comment]
It helped, but now `npm run build` yields:

```
Error happened when running command /path/to/project/oni/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world' ]
```

**Comment by bryphe** [comment]
Glad that original error is resolved!

For the `bsb.exe` error - I'm actually not sure what causes it. It used to happen on my Ubuntu box but it no longer occurs for me. You can try deleting the `node_modules` folder and running `npm install` again.

Alternatively, that one is safe to ignore - you can run Oni with that error (that build step is for the `reason` / `ocaml` plugin, so as long as you aren't using that you're okay).

**Comment by TalAmuyal** [comment]
Tried removing the `node_modules` folder, now `npm install` generates:

```
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! bs-platform@1.8.0 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bs-platform@1.8.0 postinstall script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bs-platform package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bs-platform
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bs-platform
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

:(

**Comment by bryphe** [comment]
Hmm, would you mind including the full error log? `npm install --loglevel verbose` should save a `npm-debug.log`.

In addition, what node version are you using? `node --version` and `npm --version`?

There are several issues in the bucklescript repo related to this, like:
- bucklescript/bucklescript#773
- bucklescript/bucklescript#2051
- bucklescript/bucklescript#1446

In addition, looks like there is a newer version of `bs-platform` (we're on `1.8.0`, looks like it's up to `1.9.3` now - might be worth trying that out...)

**Comment by TalAmuyal** [comment]
Well, tried `rm -rf node_modules && npm install --loglevel verbose && npm run start` a few times and now it works...

Doesn't seems to be a good thing though...

Will try a few more things and report back.

**Comment by bryphe** [comment]
Interesting... I'm glad that you got it working! It's always a bit disconcerting when it starts working magically, though... 😄

**Comment by bryphe** [comment]
I'll close this out since @TalAmuyal since it started working... but let me know if you hit this again or there is any new info we can use to troubleshoot.
